example/config/routes.rb
Example::Application.routes.draw do
  root   to: 'widgets#index', as: 'root'
  get    'widgets/new', to: 'widgets#new', as: 'new_widget'
  post   'widgets', to: 'widgets#create', as: 'widgets'
  get    'widgets/:id/thumbnail', to: 'widgets#thumbnail', as: 'widget_thumbnail'
  get    'widgets/:id/manual', to: 'widgets#manual', as: 'widget_manual'
  get    'widgets/:id/photo', to: 'widgets#photo', as: 'widget_photo'
  delete 'widgets/:id', to: 'widgets#destroy', as: 'widget'
  get    'widgets/:id/edit', to: 'widgets#edit', as: 'edit_widget'
  patch  'widgets/:id', to: 'widgets#update'
end

example/app/models/midden.rb
class Midden < ActiveRecord::Base
  include EchoUploads::Model
  
  belongs_to :squib
  
  echo_upload :thumbnail, write_tmp_file: :after_validation
  echo_upload :manual, write_tmp_file: false
  
  validates :name, presence: true, length: {maximum: 255}
  
  attr_accessor :callback_invoked
  
  after_echo_uploads_write_prm do |midden|
    midden.callback_invoked = true
  end
end

example/app/models/snark.rb
class Snark < ActiveRecord::Base
  include EchoUploads::Model
  
  echo_upload :manual, storage: EchoUploads::S3Store
  
  validates :manual, upload: {presence: true}
end

example/app/models/squib.rb
class Squib < ActiveRecord::Base
  include EchoUploads::Callbacks
  
  has_many :middens
  
  accepts_nested_attributes_for :middens, reject_if: :all_blank
  
  after_failed_save :write_midden_tmp_files
  
  def write_midden_tmp_files
    middens.each do |midden|
      midden.maybe_write_tmp_thumbnail
      midden.maybe_write_tmp_manual
    end
  end
end

example/app/models/widget.rb
require 'fileutils'

class Widget < ActiveRecord::Base
  include EchoUploads::Model
  
  echo_upload :manual
  echo_upload :warranty, map: :reverse_warranty
  echo_upload :thumbnail
  echo_upload :photo, map: :resize_photo, multiple: true
  
  validates :name, presence: true, length: {maximum: 255}
  validates :thumbnail, upload: {presence: true, max_size: 1.5.kilobytes, extension: ['.jpg', '.png']}
  
  private
  
  def resize_photo(in_file, mapper)
    in_image = ChunkyPNG::Image.from_file(in_file.path)
    
    [200, 300].each do |size|
      mapper.write('.png') do |out_file_path|
        in_image.resample_nearest_neighbor(size, size).save(out_file_path)
      end
    end
  end
  
  def reverse_warranty(in_file, mapper)
    mapper.write('.txt') do |out_file_path|
      File.open(out_file_path, 'w') do |f|
        f << in_file.read.reverse
      end
    end
  end
end

example/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

example/app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  def create
    @widget = Widget.new widget_params
    if @widget.save
      redirect_to root_url, notice: 'Widget created.'
    else
      render action: :edit
    end
  end
  
  def destroy
    Widget.find(params[:id]).destroy
    redirect_to root_url, notice: 'Widget deleted.'
  end
  
  def edit
    @widget = Widget.find params[:id]
  end
  
  def index
    @widgets = Widget.order('id DESC')
  end
  
  def new
    @widget = Widget.new
    render action: :edit
  end
  
  def manual
    # We find the Widget by its ID. Alternatively, we could have had this method use
    # params[:key], which is the digest of the file. In that case, instead of calling a
    # finder on Widget, we'd call a finder on EchoUploads::File. The behavior would be
    # the same for the most part--except when a user follows an old link to an widget whose
    # contents have changed. 
    widget = Widget.find params[:id]
    send_file widget.manual_path, type: widget.manual_mime, disposition: 'inline', filename: widget.manual_original_filename
  end
  
  def photo
    # See comment in #manual action.
    widget = Widget.find params[:id]
    send_file widget.photo_path, type: widget.photo_mime, disposition: 'inline', filename: widget.photo_original_filename
  end
  
  def thumbnail
    # See comment in #manual action.
    widget = Widget.find params[:id]
    send_file widget.thumbnail_path, type: widget.thumbnail_mime, disposition: 'inline', filename: widget.thumbnail_original_filename
  end
  
  def update
    @widget = Widget.find params[:id]
    if @widget.update_attributes widget_params
      redirect_to root_url, notice: 'Widget updated.'
    else
      render action: :edit
    end
  end
  
  private
  
  def widget_params
    params.require(:widget).permit(:manual, :thumbnail, :photo, :name, :echo_uploads_data)
  end
end

example/app/helpers/application_helper.rb
module ApplicationHelper
  def error_on(obj, attr)
    if obj.errors.include? attr
      content_tag('span', :class => 'error-message') do
        obj.errors[attr].join('; ')
      end
    else
      nil
    end
  end
  
  def widget_photo(widget)
    image_tag widget_photo_url(widget, key: widget.photo_key), alt: 'Photo'
  end
  
  def widget_thumbnail(widget)
    image_tag widget_thumbnail_url(widget, key: widget.thumbnail_key), alt: 'Thumbnail'
  end
end

example/app/views/images/edit.html.erb
<%= form_for @image do |f| %>
  <div>
    <%= f.label :name, 'Name:' %>
    <%= f.text_field :name %>
    <%= error_on f.object, :name %>
  </div>
  
  <div>
    <% if f.object.has_prm_file? %>
      <!-- If a permanent file has previously been saved, we display it back for the
      user's reference. -->
      <%= image_tag image_url(@image, key: @image.file_key) %>
    <% end %>
    
    <!-- If a temporary file has been saved, then we're redisplaying the form due to a
    validation error. (But not an error on the file itself.) We prefer not to invite the
    user to re-upload the file. -->
    <% unless f.object.has_tmp_file? %>
      <%= f.label :file, 'Image file:' %>
      <%= f.file_field :file %>
      <%= error_on f.object, :file %>
    <% end %>
  </div>
  
  <div>
    <%= f.hidden_field :echo_uploads_data %>
    <!--
      Decoded value of #echo_uploads_data:
      <%= Base64.decode64(f.object.echo_uploads_data) %>
    -->
    <%= f.submit 'Save' %>
  </div>
<% end %>

example/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Example</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  
  <body>
    <div id="container">
      <%= yield %>
    </div>
  </body>
</html>

example/app/views/widgets/edit.html.erb
<%= form_for @widget do |f| %>
  <div>
    <%= f.label :name, 'Name:' %>
    <%= f.text_field :name %>
    <%= error_on f.object, :name %>
  </div>
  
  <div>
    <% if f.object.has_prm_thumbnail? %>
      <!-- If a permanent file has previously been saved, we display it back for the
      user's reference. -->
      <%= widget_thumbnail f.object %>
    <% end %>
    
    <!-- If a temporary file has been saved, then we're redisplaying the form due to a
    validation error. (But not an error on the file itself.) We prefer not to invite the
    user to re-upload the file. -->
    <% unless f.object.has_tmp_thumbnail? %>
      <%= f.label :file, 'Thumbnail file:' %>
      <%= f.file_field :thumbnail %>
      <%= error_on f.object, :thumbnail %>
    <% end %>
  </div>
  
  <div>
    <% if f.object.has_prm_photo? %>  
      <%= widget_photo f.object %>
    <% end %>
    
    <% unless f.object.has_tmp_photo? %>
      <%= f.label :file, 'Photo file:' %>
      <%= f.file_field :photo %>
      <%= error_on f.object, :photo %>
    <% end %>
  </div>
  
  <div>
    <%= f.hidden_field :echo_uploads_data %>
    <!--
      Decoded value of #echo_uploads_data:
      <%= Base64.decode64(f.object.echo_uploads_data) %>
    -->
    <%= f.submit 'Save' %>
  </div>
<% end %>

example/app/views/widgets/index.html.erb
<p><%= link_to 'New widget', new_widget_url %></p>

<ul id="widgets">
  <% @widgets.each do |widget| %>
    <li>
      <%= widget_thumbnail widget %>
      <div class="name"><%= widget.name %></div>
      <%= link_to 'Edit', edit_widget_url(widget), class: 'edit' %>
      <%= button_to 'Delete', widget_url(widget), method: :delete %>
    </li>
  <% end %> 
</ul>